kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: git-repo-secret
  namespace: argocd
  creationTimestamp: null
spec:
  template:
    metadata:
      name: git-repo-secret
      namespace: argocd
      creationTimestamp: null
    data: null
  encryptedData:
    HTTPS_PASSWORD: AgCBNCC85zt41zgGpOR97/Kl5sBIF3mNoCHfnajzMHTfxLiSlO9chkp5iyN7c9lbgEE4KQgAX/Hx/0Ar9p3TVBDRfEQGGqzkPHyFINCClRVIzjFp09Ky7Ac5YX7q6/vNMkFfcQHaSQa9M3Kb+Hs+zMCwqccfOJMVQVaXDyT6aL8NeDOfI3S8c/NbHkVbyiUq+jyTRQV35++9aVXaM5IHEPZ0jLXexRHL6O1IEIYT/iaKf/IFPw0j4ObDid3oHHUUqab+QuFtAkLDU+l2/4g60VrHo+4mxnYTf5voYKll050URqWy+H/MtyNn3sXd1PFMfTlXfjzuQlBM73WOc59+jmRrEIdC18G1K6PYGYUw9Z2IapHnSkyWvVDwUq1w17SEmgOuK0VV64CJtBb7lqgwu+kHE3a19OyUXodaS71MW0HMi/V1L5RyqUHeIWPv4iHEvQh0maAjsil3zbXMEyz+FRpQZxF99nSirOcTU6eB46oBN/Yd2j1ezZpOCZmlP4ER7Up8JOt1epJYafG4mFkgSQPWjjaB8hebP7Sby9hUXzG9lnWwq6W1LAVA7RoHAuTUdiHuTETiG0FvyomUkauo8J05etGCAcaj2jH2sI5cstjcnBdvlxHWYHIO7dJKujShW/ncbSFSDVphWI9jexPviUwBS7SsF0JyzIjq8495rM/Oh4RTbYkv9FubhjcNEv7YzMlowwxYSCa6gZswFWo044+/X7XYYIEo3e0=
    HTTPS_USERNAME: AgBbKnu24u0m9qsUSivOzC//sY2YCxNAsfJijreTf06j0VimP+3CUGx2Oz0Jcj+eiMT3B4wkKh6ZLZ5DOnxYi9EJnyDni9J3HliLG+JUj+MBIdi+XN5TldpkHIkXzAUHyIWijgsCHeBd66qfFRvyWrBNuxKj7NyLCH9ljR/F+gHOiaD0mEKRlSBpbuCCAwYGlzeoC7MhAtN4r5bTRUT2yvdNVZ5SgfX13rBIhHKDUzydpnQokwsJ+GHutmU8oi/dXkztZUsyua/nv1R2yuUUoEVgurkKMUo+BYOAqfCfu2qNNV86RoeupqWUUyfu/bBucmMRGIHzqZvB8glh0P8TsyxG19mD1fnS0SSgEVCiY8y8dsS28jjtqJf+i5wLSloHBWCl6TdHZtd61qisvLAxCn4CbM7D6LjwpIfgJh+LgW9+EzbMgq3v4ZHnecsw+Sv5Ouy/Qu19ELUeEmErAYercYkKlkM2YNZowo7zWle0TqY4ujfez8m0VGXlBvLt1LMckQ4ZqKB6g5A4+ls+jZ9p9LyFgmgqq8P9b/rjSNEhI7O9GEYb+5+bmKjTJF2wAZv1CQ9vzRzSXY+IMnz/HRNEJA56B5hQpG+oe2tni//Zf7lsQU/HuRLpOJNePZ1CLBWvzfq9a5duE68AFDU4WEeKOKCveRuUQs1i8U0C1dJ+aMS2PXieTraxFqExKKJZI7RXMFdAmzQAzs1Al2Zwhrrs/RMK
