kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: git-repo-secret
  namespace: argocd
  creationTimestamp: null
spec:
  template:
    metadata:
      name: git-repo-secret
      namespace: argocd
      creationTimestamp: null
    data: null
  encryptedData:
    HTTPS_PASSWORD: AgCLerzeB4DEJysuokFeKI/g7eQ9AyOJtGfE28xG+rLw3ku2ORTHv1lI3/r7ETDlaMutgNQSy4EmtMFBGDDhyize/DukBj3j0gyN6V5XkRBvLsa6gdVU2Ndu9e4KEL5KmhgYC/J0g4+Hn3l7V7XyiXviKn/hT269kmYi0qMP2O4w1S2hsyaPuT1hzFPM1rx/n5shy3PlMNvQzZziJwmyC22ZqZSZofVDcQ1hkaQWjR1wuh4VhFzYTuXIwgEDJKJxXFyK90nKUvpZd8JxtPjhbWbTF73qO/FCZ+7VBObTJr2P63yIRU3Ygd0RF2HKe6h3fkAcmQnBw3Fz1OuazPBuGmYoIAy5bTOqf11uMY3DWABYYQEW21WgNr5Q5lGFQo20N1kj2ufC2bOzlF/Z4XdCPsI6aP+ook5waNTFtpmd8+1qR4mygUD+4NZAOxG1ZKJR39AifkrasCf3t3V5j3iEHFtqrj4/bVXxF6xpihWSTB3ONAmBiocb03BkZD0JleOmp/skAauXSUDaMNs3qjMeDq/IXRoVi/ibLKh0f7ETCyRasdKz9B4yGb274YIUfss/8lx3LxcrYUBC82yu8zn8Clq/OSk5ZTPTWjx3nipf/O461OTKxV1qa9Rtoj8fpfewCEiMJUb2aXtlh0FQY3zBFwfrdYzmhZjhnUlfm4Gor2AtswuWdIdwSXJHtlL4EHT4CRs3938XuGfgghUQliyX9gq4lDU6rvbvvlM=
    HTTPS_USERNAME: AgCoNSb8/tNyQQoG9MV62aKhSva4lytiOWOc9igqYfUpspnsnRYg4xoXHYxcMnGoQEm7fKm+UYpK0oeC2j6XtFaysVpolWZ6L6M0cARy4IBtL2xf5gl9bWOHgTz31+7doeQYxFHG3zXTJOuWFr/5uu593c5Om7eG6z6cP+0oxNRK/ZMnXQGgSJoMr+clQEs5VTNUE5GRnGg3PgwvgHAIVGyNvb6YmXVf6nkYrR8JCOBkEXGwWPBbptF8eWLA/aSdElLryfQT3fMYn1tCWO2PwmaZ1Z+lmBo7WKUTKrE0GS4hlEWgcGoPwG2UKx8CiBZcQuQ3ICjS7cIqfkHMlNda4h7g4oW0pyf0pMo2ngBdAljErip47apqMY1A4lD9QNE9RtlKWCWEy17Ou6mq7q5W1YYx1fGs8E8IeDqVRInnzAaIGvlgK9w26ODvAU2iuzdMnf7932x967KCWDUTsFjctFWPZNq61clU68KPlUJru7gi1OYbqQBJaF0Q4kUI2+AzBVPWTmTIGzm8w9mwrGJP+cBm29MmN8tJpF8+i8MwXNkgvX3064c6UCM24D15Hfe1uVY3Kl9a90GGBmag1CwjYQyG2QLWhOORc9D+bF5nxpqL4xZ9wHDSs08TGxLtNe5ORXEtCKvxHJ7lZf5ebSEpjYuegMKLPAVvNfH8+yaiAyNjNWEMhh8/f3lt1lQiwsFgyTcyf0iZ51KRMzWveQ4ie+pV
