kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgBAn/mAOl14L8nkGP9l62JAmw+fT6L2SpJbgw3+vuMTc/wWZMTTZzXxJqDxZM+kMneuZDVE+R7CbA3QBR9H9rDVA7htwUerpLeaszQm3se0hclEfVy6/pOOlskx0Byq2NgUiX8P6L37bIyElwhbGBZ6tN2xq/36Q7Z7lKoAveYJ4/XkWSTZAEIG837D4RdDRTSXTWVs0NSZjgERZfLUM5FoxI7GlD1twi6j7zki0Y/UHJHiL39++guYJFTjW8NzrXTku6APnza3RU8FZkvcFRM7oNgWUbLaApFSZebiJEXaaJk1L4ffCPij08BaqajvqfYiylsbzcPSWUa+ysO75Fa0HQhGEjsdYV6+Gu4RP9aJ78b+2l6DIQAPuDOPpR6DLUgSMsONrN2JavQSYoEysDS3/ZoSRr+CJPEJNeKHTVwzE0Dn/8VvBkSpghjtProWQJG7SR4zqhvw5/akSTbgpPlCnV3eq/DnTX8hIw0sDt3eDKJ0IUDgKYMpMY9HQxp33fXLqYAhiRVcPK6JTWsnoTwoludSVo2kFqrkkrCQihOnhnOYINaw2AHHoK3dtkQ8NcHx3P+ZLe/HWfK8Mdx7mO8o121YoEva8ytqvmv3rr2W7KSpJHKIciDhdgViJNsFHTV8Cp1y3WxT4m4wctdEQ9WdFAt9kb0LvMEmatslvwaYxeJMtt/G1tNm8RpjghIVnBcMduiTxrNt3jo3UZS2gN4srtT1wX0HFZcukmkNmnP6Fg==
    postgresql-postgres-password: AgAnTIE+1i1RuxKtAMtCUYxlwZzNSDBDy9Ds1fIIXfZbM2pcOJq6Bcdo75DU/WM2/bu7Zx+QIll0r+s53qjys7qLmYpi5usJhswfTLgXU5VTHLH+9uCKyc12pb95WcJf4T7ETfIL0e9hxBj1rqanc5H0MQQHFwWqEhlyMFQQ8WAe258JWNzLHA/pEYfnLBXmJ/01xVBqveQ9ZyFIzY09JEVfrSeJK8Lhz3B0BotGWK1rcIrS+mzCwfq4CHh4+eG7kAkOGdA+YL5YAK885FMhu6NJBgpOejNKWDeldSdYFFYoHZegO3/iUX9GS3F8CKNyW0s4FMzRjda132hUEWrZmM7owxz7B7ogeR9Sxq/K+nFRMe5osefpdbN0rD8JV+fR38bQIUy7JLa+1Om/WErQ9l9Sa8pDkIXT613Z42L9ZrdlncuSgHvwEQNfj5AnEzzrJbFZY040WyaEJgTgB/UC4pFuoqeeLMlKm81U0RfdnEoOhjcqWZKQ5dr9JK1Ph+P/mP8VN55V8HNAbvEF6pPpERiXv+5mrZHmwmPfIPPXEZ7RdBky3qDD5RW6UoEldFae8uUqaektdL60Cbx5/VwjSowht5d8zPD6lUSR6ma1ifroNLwvP3n4uZyD9dCRGfZyThZ9LZwL2Xnxz7m/PLqTU3blNd1X+VS0VkxaSxkUE2n+bWaPa+fRW2VY6TV+GOasmZr4XLMt0tlk9yZO7/FQ6kh/sQGPfnFpkjzg01nMV6Iuxg==
