kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCknu8uFZ4/fkA4rZ+2JIjUrhL2fIGYQNMD05JlXmS0SHoC9vCRtoRKE7m5Qa7ipVRSUpy1/TfoUxoo9FZ8KYGveNSMPIicdNOQpDMSCWcfbEgLXfwBvZOD2T/Ys/EOMLxbClB6z4VaY/blJMWM386Z7UxkIvZz/SmzfkJ0/3Wb/1ubEfcR5kzLHBu4tp0ZiVcE53XEqJRW179o+c9tbsAl2tYRYrweQCq4k81s7kqosyBj+R0A7HY0M37owmfrASlBe+M46hBPbbyqe5miMRxxvOVpL2bm9zTQ50n7kdSyxw93QZR7mQRz5citCjFMTNqnsg1VBZl6HpXecW2lgXvak7RDiaMmkhREbO8Cfl4xZlhtyU3vWlO9cbcSyq8aom8pYxdMXFtyxCUcGgLtDSHxvtsJba9OdAiqcblvJId+28GvbAC2a0SYEpjAbdSidweYHkSZZs/Raqf6lr5dX44J9Xnvn0WxEjDdZ9Gj9zCXVL8KQ6DBmWRi6iG7xTsrTIiP6FSvxDKUmPcmpfqEbc9zC0fbzT4a3aY4Sirk/P192Yj0RkULoo2I+D9NwK2LKqjrMmJkmkr1xWCDWl1WyBsoQObp9+pwWlMYjD+BirXQUNjBYj2vy5KxLgV89zlEkLdzadd5tcRSvDKXGFkH0DqKML2/URcXUx3PJlB0CS+zKAMlhnV2ns3UHRX/HaSGrLk=
    admin-user: AgBwsYi0LM0SsQeYNK4ZtzgB7iDBPzy7F+uEeSh2MOauk0uZOHcxJaQJj3ixDcDhrZ7oB1OfTVwb+LQ0/ONrZ4oHvckOv3QPfSRb23YrhLc111AeuqjQl1KKk+i3r6FeM10C5TFItEqFsbKRZ3XCjV1peDL4wFptxMxxc16iwbOpyEtEz9ViaquoFUwz8UrtLnf8SeXtTe3+rGcQnvJ9hiXQ1yeQyjT+wZxUQm3sjkHQOsA0YaE5eYTe8dIF3t5mE5Hxj41m3wOczA9HAenubUnTCiAge2N0TODFVLyw+1zTjXtMws0mT/qHTWjZCa+8Dshj8MghZU7+M4cJkTAHbfXLIETOMXRT7dVmSwwNi9u7oL1YAVa67cs5Azhf8u5Kq2YR9hhW+MTYaXHpkY5KY0oKTz2npWWjzKOK8I3KalYANjii8jl/P6y75PwxhplYmPOg7x/8oiuCl+txn+JQFVK2XT8dTxXoRhfOyA9p1/VU7laXeL4LXrdjb/Y9f9yInV+Ri/Pgx2TIzyfNpSPSjAowwC3K0JvRoXgVm28g1QKOCLqACM+U4pAQKz07vCNfeQOt1YDcDB72670L81PLxb9umb31sHzGL0kdEtc9z8PvYAEulEbpldW1du7xdy9Q28CXZYY7esenHkeDj1sH4cHtNyEC7Lz3ujnqbszQLpYRddmIB0s1mEW7hl6Bk2JsDJQ=
