kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgAyao26yQS/h6coo6gsrGpmr6xkfYH1Dtw/o2HC95AK69OTMDMipPBEHhD9r8XFR7HIcTInVoPJBYv+jq8qrzcufkCbjmDk9pI0oFu/hLVMd77cqRJeQukBhL+g5E+doHFmsoFgzuxLnIgEh7JxnH/RQMaI5kRFMFsgKXvC+Jd3lQHXgWzhPx6sFSBPw66eVxfUixkyGAT+0z0Vp6ShEVq7uATH/jOM3pr3c3aBIfbCrLs3TilWNKiNaOtr0StWm63EFNA8lT77v+fXOs4bpAzOfv4omWk1tx8xKJwYqbGUGlu+LMUadQ1CWMB6B6wpk7GaWOnMxXsDmabZn0y8Ce33KS2Vu3iNlOkVfhz0NPTBF1aJcOzMYkdUGr1eOmf2ckkgH43+XDtW/eAcPi4PO5i+SVnCrmqKcZnSTSAxpNWNVWHXy7XIdJuHlUcthbpLLtKxi2r37wSFH0j2i7I0DRLNliHf331KZbh7Jzo7pmWJ2C2AOpqRQ7gTY/dRI12rMhCLO23WqTsBox/Ro7LSAe01C7zTMNUnGTNNI4tPG/fp2YdbzjdTqO6jNeGyxhpqAIFwfYuus0ETS20geo1Hn08fqWUyHhHOiL0LYLx0RLg0WwXCycpsoPdG7HCsXmJT2Qer874pY/WnBBvhcl6xcF8++aVcC0rvhkmanFbhlutuBIQkl2Vi3bWlxZ3WNpMP19k=
    admin-user: AgALi82fA5Yndi6jh7ET+GTeefZ0YkgSuZCKvynbNVdBth26P4u/eBUAu6pDrsIf6v022Giaqy19GK8JhR2gXQh3fNNg7k1pg4gS9OHfha0toUsa7JP3TtpdX4hzryoBNRxe3cxJvvwrRkXWT2eyGaVMaNO9B3NJCA4jyaIun/LbzrlMM+oWjqiflZL53N/2gno0vCVRmrN26k8X1LUS2W2OVoCTK3f4s3ADxcWiOK8UzAlTW5o9mo8+EeI9ekea1w6+q/xluEs63XRiQyrRj8f3Rjyrrrg/M7XTCXF1Rqpi5WXswNGQuRHBs7ZHO9YzL6mj/hoi8xzld7QqUAHuRWNOlli419wbmy/tLvWyc/6MDFsSBdZzlWElDD9lam0YvT9vEH0a5bxTH5oMTjRL4+tQhB73CRsphBrZMpcqf1F3ER7DKUfrzJ6A8igpa93GavWo5NeHleSq5up8LEDLL99KzxzSw4HKkz9XI9G6vL/9/OqjSBdkl5HHWlC5fnN0okUzeo58XIauXV7/m32bSyZM2asrXvI/Nf3v8aJ1/xRdiiCNiZJBFjYGpZBEhG+KpXFzCm3Fxxyy+S4JFT1F30mgTUKiMk9YSGOE0l+ARNxGMmMdn3F/XHlPkGMWzAqKkM1pf0nvxJrSr6obZtvRwjrefR7w0cAle00y1VcDsNmK2pKEEvRvoRxlanHUa0RNNNU=
